In [1]:
# imports 

import pandas as pd 
import numpy as np

In [5]:
data = pd.read_excel('../data/Cat_personality_data.xlsx')

In [6]:
data

,Personality1_Vigilant,Personality2_Stable,Personality3_Bold,Personality4_Clumsy,Personality5_Defiant,Personality6_Gentle,Personality7_Constrained,Personality8_Inquisitive,Personality9_Inventive,Personality10_Irritable,...,Personality45_Decisive,Personality46_Self_assured,Personality47_Anxious,Personality48_Trusting,Personality49_Active,Personality50_Cooperative,Personality51_Shy,Personality52_Eccentric,Country,Cat_sex
0,6,5,7,5,5,6,1,5,4,3,...,4,6,4,5,7,2,2,4,NewZealand,Male
1,7,3,4,1,7,7,3,4,3,2,...,4,3,6,6,1,6,2,5,NewZealand,Female
2,7,5,7,1,2,3,3,7,7,2,...,7,6,3,4,7,2,3,4,Australia,Male
3,7,4,1,1,7,2,7,1,3,7,...,5,3,3,2,2,2,6,2,Australia,Female
4,5,7,7,1,4,7,7,4,4,1,...,5,7,1,7,7,6,2,7,Australia,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2797,5,6,4,1,1,3,5,6,4,2,...,6,6,2,4,7,5,3,1,NewZealand,Male
2798,5,7,6,1,2,6,6,3,2,1,...,5,6,1,6,1,3,4,1,NewZealand,Female
2799,6,5,5,1,2,6,2,5,5,1,...,5,5,2,5,5,4,2,4,NewZealand,Female
2800,6,6,5,1,1,7,4,5,6,2,...,6,6,1,2,5,5,5,3,NewZealand,Female
2801,7,6,5,2,2,6,6,6,4,2,...,5,6,2,6,6,5,4,2,NewZealand,Male